core/urls.py
from django.shortcuts import render_to_response
from django.urls import path, re_path, include
from django.contrib.auth.decorators import login_required
from .views import (
    ItemDetailView,
    CheckoutViewV2,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    BitpayView,
    #PaymentStripeView,
    #PaymentMainView,
    AddCouponView,
    RequestRefundView,
    OrderView,
    AllOrderView,
    DisableView,
    AccountView,
    PaypalPaymentProcess,
    payment_done,
    payment_canceled,
    bitpay_notify,
    coinbase_notify,
    CoinbaseView
)

app_name = 'core'

urlpatterns = [
    path('', login_required(HomeView.as_view()), name='home'),
    path('checkout/', login_required(CheckoutViewV2.as_view()), name='checkout'),
    path('order-summary/', login_required(OrderSummaryView.as_view()), name='order-summary'),
    path('orders/', login_required(OrderView.as_view()), name='user-orders'),
    path('all-orders/', login_required(AllOrderView.as_view()), name='all-orders'),
    path('accounts/', login_required(AccountView.as_view()), name='accounts'),
    path('disable/', login_required(DisableView.as_view()), name='disable'),
    path('product/<slug>/', login_required(ItemDetailView.as_view()), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', login_required(AddCouponView.as_view()), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    #path('payment/', login_required(PaymentStripeView.as_view()), name='payment-stripe'),
    path('payment/', login_required(PaymentView.as_view()), name='payment'),
    path('bitpay/', login_required(BitpayView.as_view()), name='bitpay'),
    path('bitpay-notify/', bitpay_notify, name='bitpay-notify'),
    path('coinbase-notify', coinbase_notify, name='coinbase-notify'),
    path('coinbase/', login_required(CoinbaseView.as_view()), name='coinbase'),
    path('request-refund/', login_required(RequestRefundView.as_view()), name='request-refund'),
    re_path(r'^paypal/',include('paypal.standard.ipn.urls')),
    re_path(r'^process/$', login_required(PaypalPaymentProcess.as_view()), name='process'),
    re_path(r'^done/$', payment_done, name='done'),
    re_path(r'^canceled/$', payment_canceled, name='canceled')

]

def handler404(request, template_name="404.html"):
    response = render_to_response(template_name)
    response.status_code = 404
    return response

giveaways/urls.py
from django.urls import path

app_name = 'giveaways'

from giveaways.views import (
    GiveawayDetailView,
    GiveawayListView,
    GiveawayCreateView,
)

urlpatterns = [
    path("", GiveawayListView.as_view(), name="giveaway-list"),
    path("create", GiveawayCreateView.as_view(), name="giveaway-create"),
    #path("<int:pk>/", GiveawayDetailView.as_view(), name="giveaway-detail"),
    path(
        "<int:pk>-<str:slug>/",
        GiveawayDetailView.as_view(),
        name="giveaway-detail",
    ),

]

retweet_picker/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views
from .views import (
    OrdersListView,
    launch_giveaway,
    #prelaunch_validator,
    order_details,
    QueueListView,
    delete_queue,
    clear_queue,
    pick, draw, drawstop, fetch_data, import_contest, pick_entries, load_entries, load_entry_progress,
    load_all_entries, drawing_progress, draw_result
)

app_name = 'retweet_picker'

urlpatterns = [
    path('', OrdersListView.as_view(), name='giveaway-list'),
    path('new_contest/', views.new_retweet_contest, name='retweet_picker'),
    path('launch/<int:order_id>/<int:item_id>', launch_giveaway, name='launch_giveaway'),
    path('queue/', login_required(QueueListView.as_view()) , name='queue_view'),
    # path('queue/<str:queue_type>/', QueueListView.as_view() , name='queue_view'),
    path('delqueue', delete_queue , name='del_queue'),
    path('draw', draw , name='draw'),
    path('draw-result/<draw_id>', draw_result , name='draw_result'),
    path('drawstop', drawstop , name='drawstop'),
    path('drawing_progress', drawing_progress , name='drawing_progress'),
    path('fetch_data', fetch_data , name='fetch_data'),
    path('import_contest', import_contest , name='import_contest'),
    path('load_entries', load_entries , name='load_entries'),
    path('load_entry_progress', load_entry_progress , name='load_entry_progress'),
    path('load_all_entries', load_all_entries , name='load_all_entries'),
    path('draw/<int:gwid>', login_required(pick_entries) , name='pick_entries'),
    path('clearqueue', clear_queue , name='clear_queue'),
    path('order/<int:order_id>', order_details, name="order_details"),
    path('results/<int:order_id>', views.contest_results, name='contest_results'),
    #path('results/<uuid:giveaway_id>', views.contest_results, name='contest_results'),
    path('results/', views.contest_results, name='all_contest_results'),
    path('bubble_rescue/decoder_ring/<slug:secret_code>/', views.decoder_ring, name='decoder'),
    path('bubble_rescue/', views.bubble_rescue, name='bubble-rescue-5000'),
    path('import/', login_required(views.pick), name='pick'),
    path('user_settings/', login_required(views.user_settings), name='user_settings'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
]

slotapp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'slotapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('test', views.test, name='test'),
    path('test-adduser', views.test_adduser, name='test_adduser'),
    path('community', views.first_page, name='first_page'),
    path('tocart', views.tocart, name='tocart'),
    path('launch', views.launch, name='launch'),
    path('getcart', views.getcart, name='getcart'),
    path('setpause', views.setpause, name='setpause'),
    path('setusernames', views.setusernames, name='setusernames'),
    path('cartminus', views.cartminus, name='cartminus'),
    path('checkout', views.checkout, name='checkout'),
    path('get_available', views.get_available, name='get_available'),
    path('setdisable', views.setdisable, name='setdisable'),
    path('payment', views.slot_payment, name='slot_payment'),
    path('payment_execute', views.slot_payment_execute, name='slot_payment_execute'),
    path('logout', views.user_logout, name='user_logout'),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from datetime import timedelta

from django.conf import settings
from django.db import models
from django.db.models.signals import post_save
from django.shortcuts import reverse
from django.utils import timezone
from django_countries.fields import CountryField

CATEGORY_CHOICES = (
    ('GW', 'Giveaway'),
    ('PW', 'Pick Winner'),
    ('SB', 'Social Boost'),
    ('PE', 'Profile Examine')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('I', 'info'),
    ('W', 'success'),
    ('D', 'danger')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)

GIVEAWAY_STATUS_CHOICES = (
    ('I', 'In Cart'),
    ('P', 'Purchased'),
    ('S', 'Scheduled'),
    ('L', 'Live'),
    ('T', 'Winner Selected'),
    ('C', 'Winner Contacted'),
    ('D', 'Winner Paid')
)

SCHEDULER_QUEUE = (
    ('D', 'default'),
    ('L', 'low'),
    ('H', 'high')
)

PAYMENT_METHOD = (
    ('S', 'Stripe'),
    ('B', 'Braintree'),
    ('P', 'Paypal'),
    ('C', 'Bitcoin'),
    ('T', 'Credit'),
)


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user_profile')
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    braintree_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)
    twitch_account = models.CharField(max_length=250, null=True, blank=True)
    credit_display = models.BooleanField(default=True)
    
    def __str__(self):
        return str(self.user.username)


class Socials(models.Model):
    twitter = models.BooleanField(default=False)
    instagram = models.BooleanField(default=False)
    facebook = models.BooleanField(default=False)
    tiktok = models.BooleanField(default=False)
    # TODO ADD MORE SOCIALS
    # Could also integrate with socialauth so they have to have it confirmed before checkout


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    giveaway_value = models.FloatField(verbose_name="Amount to giveaway")  # Split value and fee to show amount given
    giveaway_fee = models.FloatField(verbose_name="Amount to charge buyer")
    duration_to_run = models.IntegerField(blank=True, null=True)
    # promote_socials = models.
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    available = models.BooleanField(default=True)
    priority = models.CharField(choices=SCHEDULER_QUEUE, max_length=1, default='D')
    description = models.TextField()
    image = models.ImageField()

    class Meta:
        default_related_name = 'items'
        ordering = ['-price']

    def __str__(self):
        return self.title

    def get_price(self):
        return self.giveaway_fee + self.giveaway_value

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey("Item", on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField(default=1)
    available_to_run = models.IntegerField(default=1)
    kind = models.IntegerField(default=0)
    slot = models.ForeignKey("Slotitem", on_delete=models.CASCADE, null=True)
    username = models.CharField(max_length=200, default='', blank=True, null=True)
    launch_code = models.CharField(max_length=200, blank=True, null=True)
    status = models.CharField(max_length=20, choices=GIVEAWAY_STATUS_CHOICES, default='I', blank=True, null=True)

    class Meta:
        ordering = ['-orders__id']

    def __str__(self):
        if self.kind == 0:
            return f"{self.quantity} of {self.item.title}"
        else:
            return f"{self.quantity} of {self.slot.title}"

    def get_title(self):
        if self.kind == 0:
            return self.item.title
        else:
            return self.slot.title

    def get_total_item_price(self):
        # self.user.related_field
        # self.user.account_type
        if self.kind == 0:
            price = (self.user.account_type.fee_quantifier * self.item.giveaway_fee) + self.item.giveaway_value
            # return self.quantity * self.item.get_price()
            return self.quantity * price
        else:
            return 0

    def get_total_discount_item_price(self):
        if self.kind == 0:
            return self.quantity * self.item.discount_price
        else:
            return 0

    def get_amount_saved(self):
        if self.kind == 0:
            return self.get_total_item_price() - self.get_total_discount_item_price()
        else:
            return 0

    def get_final_price(self):
        if self.kind == 0:
            if self.item.discount_price:
                return self.get_total_discount_item_price()
            return self.get_total_item_price()
        else:
            return self.quantity * self.slot.value

    def decrease_available(self):
        self.available_to_run -= 1

    def increase_available(self):
        self.available_to_run += 1


def get_deadline():
    return timezone.now() + timedelta(days=5)


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    expires_on = models.DateTimeField(default=get_deadline)
    desired_giveaway_date = models.DateTimeField(default=timezone.now, blank=True)
    ordered_date = models.DateTimeField(auto_now_add=True)
    ordered = models.BooleanField(default=False)
    kind = models.IntegerField(default=0)
    status = models.CharField(max_length=20, choices=GIVEAWAY_STATUS_CHOICES, default='I', blank=True, null=True)
    notes = models.TextField(blank=True, max_length=500)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    creditpayment = models.ForeignKey(
        'CreditPayment', related_name='paid_order', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    '''
    1. Item added to cart
    2. Adding a billing address
    (Failed checkout)
    3. Payment
    (Preprocessing, processing, packaging etc.)
    4. Being delivered
    5. Received
    6. Refunds
    '''

    class Meta:
        default_related_name = 'orders'
        ordering = ['-id']

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total

    def get_available_runs(self):
        # return ', '.join([x.item.title for x in self.items.all()])
        return ', '.join([x.item.title for x in self.items.filter(kind=0)])

    def get_purchased_items(self):
        # return ', '.join([x.item.title for x in self.items.all()])
        if self.kind == 0:
            return ', '.join([x.item.title for x in self.items.filter(kind=0).select_related('item')])
        else:
            return ', '.join([x.slot.title for x in self.items.filter(kind=1).select_related('item')])

    def get_items_sum(self):
        # return sum([y.quantity for y in self.items.all()])
        if self.kind == 0:
            return sum([y.quantity for y in self.items.filter(kind=0)])
        else:
            return sum([y.quantity for y in self.items.filter(kind=1)])


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'

class CreditPayment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    usd_amount = models.FloatField(default=0)
    credit_amount = models.FloatField(default=0)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        if self.user:
            return self.user.username + " : " + str(self.credit_amount)
        else:
            return '_' + " : " + str(self.credit_amount)
        

class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)

templates/core/alerts.html
{% if messages %}
    {% for message in messages %}
        {% if message.level_tag == "warning" %}
            <script>Swal.fire({
                title:'Warning!',
                text:'{{ message }}',
                buttons:"false",
                type:'{{ message.level_tag }}',
                showConfirmButton: true,
                timerProgressBar: true,
                timer:5000})</script>
        {% elif message.level_tag == "success" and "order_complete" in message.extra_tags %}
            <script>
                Swal.fire({
                title:'Order Complete!',
                text:'{{ message }}',
                buttons:"false",
                type:'{{ message.level_tag }}',
                timerProgressBar: true,
                showConfirmButton: true
            })</script>
        {% elif message.level_tag == "success" %}
            <script>
                Swal.fire({
                title:'SUCCESS!',
                text:'{{ message }}',
                buttons:"false",
                position: 'top-end',
                toast:true,
                type:'{{ message.level_tag }}',
                timerProgressBar: true,
                showConfirmButton: false,
                timer:3000
            })</script>
        {% elif message.level_tag == "error" and "html" in message.extra_tags%}
            <script>Swal.fire({
                type:'{{ message.level_tag }}',
                title:'Oh, No!!',
                html:'{{ message }}',
                buttons:"true",
                showConfirmButton: true,
                timerProgressBar: true,
                timer:4000
            })</script>
        {% elif message.level_tag == "error" %}
            <script>Swal.fire({
                type:'{{ message.level_tag }}',
                title:'Oh, No!!',
                text:'{{ message }}',
                buttons:"true",
                showConfirmButton: false,
                timerProgressBar: true,
                timer:3000
            })</script>

        {% else %}
            <script>Swal.fire({
                type:'{{ message.level_tag }}',
                title:'{{ message }}',
                //text:'{{ message }} ',
                buttons:"false",
                position: 'top-end',
                toast:true,
                showConfirmButton: false,
                timerProgressBar: true,
                timer:2000})
            </script>
        {% endif %}
    {% endfor %}

{% endif %}

templates/core/footer.html
<!-- ============================================================== -->
<!-- footer -->
<!-- ============================================================== -->
<footer class="footer">
<!--MONUMETRIC In-Screen / Sticky Footer D:728x90 T:728x90 M:320x50,320x100 START-->

<div id="mmt-fadf46fd-f556-431c-904c-3062618ee09e"></div><script type="text/javascript" data-cfasync="false">$MMT = window.$MMT || {}; $MMT.cmd = $MMT.cmd || [];$MMT.cmd.push(function(){ $MMT.display.slots.push(["fadf46fd-f556-431c-904c-3062618ee09e"]); })</script>

<!--MONUMETRIC In-Screen / Sticky Footer D:728x90 T:728x90 M:320x50,320x100  ENDS-->    © 2020 gridgaming.io
</footer>
<!-- ============================================================== -->
<!-- End footer -->
<!-- ============================================================== -->

templates/core/left-sidebar.html
<!-- ============================================================== -->
<!-- Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->
{% if user.is_authenticated %}
    <aside class="left-sidebar" data-sidebarbg="skin1">
        <!-- Sidebar scroll-->
        <div class="scroll-sidebar">
            <!-- Sidebar navigation-->
            <nav class="sidebar-nav">
                <ul id="sidebarnav">
                    <!-- User Profile-->
                    <li class="sidebar-item"><a class="sidebar-link waves-effect waves-dark" data-toggle="tooltip"
                                                data-placement="bottom" title
                                                data-original-title="Grow your twitter following and brand!"
                                                href="{% url 'core:home' %}" aria-expanded="false"><i
                            class="mdi mdi-twitter"></i><span class="hide-menu">Sponsor</span></a></li>
                    <li class="sidebar-item"><a class="sidebar-link waves-effect waves-dark" data-toggle="tooltip"
                                                data-placement="bottom" title
                                                data-original-title="Launch your giveaway after you purchase"
                                                href="{% url 'retweet_picker:giveaway-list' %}" aria-expanded="false"><i
                        class="mdi mdi-rocket"></i><span class="hide-menu">Launch</span></a></li>
                    <li class="sidebar-item"><a class="sidebar-link waves-effect waves-dark" data-toggle="tooltip"
                                                data-placement="bottom" title
                                                data-original-title="Join a community giveaway (limited availability)"
                                                href="{% url 'slotapp:first_page' %}" aria-expanded="false"><i
                        class="mdi mdi-human-handsup"></i><span class="hide-menu">Community</span></a></li>
{#                    <li class="sidebar-item"><a class="sidebar-link waves-effect waves-dark" data-toggle="tooltip"#}
{#                                                data-placement="bottom" title#}
{#                                                data-original-title="Review your orders. Email business@gridgaming.io if you need support"#}
{#                                                href="{% url 'core:user-orders' %}" aria-expanded="false"><i#}
{#                        class="mdi mdi-reorder-horizontal"></i><span class="hide-menu">Orders</span></a></li>#}
                    <li class="sidebar-item"><a class="sidebar-link waves-effect waves-dark" data-toggle="tooltip"
                                data-placement="bottom" title
                                data-original-title="All current giveaways!"
                                href="{% url 'giveaways:giveaway-list' %}" aria-expanded="false"><i
                        class="mdi mdi-cash"></i><span class="hide-menu">Giveaways</span></a></li>
                        {#                <li class="sidebar-item"> <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false"><i class="mdi mdi-gauge"></i><span class="hide-menu">Dashboard </span></a>#}
                        {% if request.user.is_staff %}
                            <li class="sidebar-item nav-item dropdown">
                                <a class="nav-link dropdown-toggle sidebar-link waves-effect waves-dark text-light-warning"
                                   href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                                   aria-haspopup="true" aria-expanded="false">
                                    STAFF
                                </a>
                                <div class="sidebar-item dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item sidebar-link waves-effect waves-dark" data-toggle="tooltip"
                                       data-placement="bottom" title
                                       data-original-title="Staff only: Review all community orders"
                                       href="{% url 'core:all-orders' %}" aria-expanded="false"><i
                                            class="mdi mdi-marker-check"></i><span class="hide-menu">All Community Orders</span></a>
                                    <a class="dropdown-item sidebar-link waves-effect waves-dark" data-toggle="tooltip"
                                       data-placement="bottom" title
                                       data-original-title="Account information about community giveaway participants"
                                       href="{% url 'core:accounts' %}" aria-expanded="false"><i
                                            class="mdi mdi-marker-check"></i><span class="hide-menu">Accounts</span></a>
                                    <a class="dropdown-item sidebar-link waves-effect waves-dark" data-toggle="tooltip"
                                    data-placement="bottom" title
                                    data-original-title="Giveaway launching queue list"
                                    href="{% url 'retweet_picker:queue_view' %}" aria-expanded="false"><i
                                            class="mdi mdi-rocket"></i><span class="hide-menu">View Queue</span></a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item sidebar-link waves-effect waves-dark" data-toggle="tooltip"
                                       data-placement="bottom" title
                                       data-original-title="Set available or disable items"
                                       href="{% url 'core:disable' %}" aria-expanded="false"><i
                                            class="mdi mdi-block-helper"></i><span
                                            class="hide-menu">Available/Disable</span></a>
                                    <a class="dropdown-item sidebar-link waves-effect waves-dark" data-toggle="tooltip"
                                       data-placement="bottom" title
                                       data-original-title="Set users' settings"
                                       href="{% url 'retweet_picker:user_settings' %}" aria-expanded="false"><i
                                            class="mdi mdi-account-settings-variant"></i><span
                                            class="hide-menu">User Settings</span></a>

                                </div>
                            </li>
                            <!-- <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark" href="https://www.gridgaming.io/gridadmin/core/order/" aria-expanded="false"><i class="mdi zmdi-money-box"></i><span class="hide-menu">Orders</span></a> -->
                            {#                            <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark" data-toggle="tooltip" data-placement="bottom" title data-original-title="Staff only: Review all community orders" href="{% url 'core:all-orders' %}" aria-expanded="false"><i class="mdi mdi-marker-check"></i><span class="hide-menu">All Community Orders</span></a>#}
                            {#                            <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark" data-toggle="tooltip" data-placement="bottom" title data-original-title="Account information about community giveaway participants" href="{% url 'core:accounts' %}" aria-expanded="false"><i class="mdi mdi-marker-check"></i><span class="hide-menu">Accounts</span></a>#}
                            {#                            <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark" data-toggle="tooltip" data-placement="bottom" title data-original-title="Set available or disable items" href="{% url 'core:disable' %}" aria-expanded="false"><i class="mdi mdi-block-helper"></i><span class="hide-menu">Available/Disable</span></a>#}
                        {% endif %}
                        <li class="sidebar-item"><a class="sidebar-link waves-effect waves-dark" data-toggle="tooltip"
                            data-placement="bottom" title
                            data-original-title="Choose winners from retweets!"
                            href="{% url 'retweet_picker:pick' %}" aria-expanded="false"><i
                        class="mdi mdi-trophy"></i><span class="hide-menu">Retweet Picker</span></a></li>
                    <!--<li class="nav-small-cap"><i class="mdi mdi-dots-horizontal"></i> <span class="hide-menu">Personal</span></li>-->
                    {#                    <ul aria-expanded="false" class="collapse  first-level">#}
                    {#                        <li class="sidebar-item">#}
                    {#                            <a href="index.html" class="sidebar-link">#}
                    {#                                <i class="mdi mdi-adjust"></i>#}
                    {#                                <span class="hide-menu"> Dashboard 1 </span>#}
                    {#                            </a>#}
                    {#                        </li>#}
                    {#                        <li class="sidebar-item">#}
                    {#                            <a href="index2.html" class="sidebar-link">#}
                    {#                                <i class="mdi mdi-adjust"></i>#}
                    {#                                <span class="hide-menu"> Dashboard 2 </span>#}
                    {#                            </a>#}
                    {#                        </li>#}
                    {#                        <li class="sidebar-item">#}
                    {#                            <a href="index3.html" class="sidebar-link">#}
                    {#                                <i class="mdi mdi-adjust"></i>#}
                    {#                                <span class="hide-menu"> Dashboard 3 </span>#}
                    {#                            </a>#}
                    {#                        </li>#}
                    {#                    </ul>#}
                    {#                </li>#}
                    {##}
                    {#                <li class="sidebar-item"> <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false"><i class="mdi mdi-trending-up"></i><span class="hide-menu">Stats</span></a>#}
                    {#                    <ul aria-expanded="false" class="collapse first-level">#}
                    {#                        <li class="sidebar-item"><a href="javascript:void(0)" class="sidebar-link"><i class="mdi mdi-octagram"></i><span class="hide-menu"> item 1.1</span></a></li>#}
                    {##}
                    {#                        </li>#}
                    {#                        <li class="sidebar-item"><a href="javascript:void(0)" class="sidebar-link"><i class="mdi mdi-playlist-check"></i><span class="hide-menu"> item 1.4</span></a></li>#}
                    {#                    </ul>#}
                    {#                </li>#}
                </ul>
            </nav>
            <!-- End Sidebar navigation -->
        </div>
        <!-- End Sidebar scroll-->
    </aside>
{% endif %}
<!-- ============================================================== -->
<!-- End Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->