core/urls.py
from django.shortcuts import render_to_response
from django.urls import path, re_path, include
from django.contrib.auth.decorators import login_required
from .views import (
    ItemDetailView,
    CheckoutViewV2,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    BitpayView,
    #PaymentStripeView,
    #PaymentMainView,
    AddCouponView,
    RequestRefundView,
    OrderView,
    AllOrderView,
    DisableView,
    AccountView,
    PaypalPaymentProcess,
    payment_done,
    payment_canceled,
    bitpay_notify,
    coinbase_notify,
    CoinbaseView
)

app_name = 'core'

urlpatterns = [
    path('', login_required(HomeView.as_view()), name='home'),
    path('checkout/', login_required(CheckoutViewV2.as_view()), name='checkout'),
    path('order-summary/', login_required(OrderSummaryView.as_view()), name='order-summary'),
    path('orders/', login_required(OrderView.as_view()), name='user-orders'),
    path('all-orders/', login_required(AllOrderView.as_view()), name='all-orders'),
    path('accounts/', login_required(AccountView.as_view()), name='accounts'),
    path('disable/', login_required(DisableView.as_view()), name='disable'),
    path('product/<slug>/', login_required(ItemDetailView.as_view()), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', login_required(AddCouponView.as_view()), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    #path('payment/', login_required(PaymentStripeView.as_view()), name='payment-stripe'),
    path('payment/', login_required(PaymentView.as_view()), name='payment'),
    path('bitpay/', login_required(BitpayView.as_view()), name='bitpay'),
    path('bitpay-notify/', bitpay_notify, name='bitpay-notify'),
    path('coinbase-notify', coinbase_notify, name='coinbase-notify'),
    path('coinbase/', login_required(CoinbaseView.as_view()), name='coinbase'),
    path('request-refund/', login_required(RequestRefundView.as_view()), name='request-refund'),
    re_path(r'^paypal/',include('paypal.standard.ipn.urls')),
    re_path(r'^process/$', login_required(PaypalPaymentProcess.as_view()), name='process'),
    re_path(r'^done/$', payment_done, name='done'),
    re_path(r'^canceled/$', payment_canceled, name='canceled')

]

def handler404(request, template_name="404.html"):
    response = render_to_response(template_name)
    response.status_code = 404
    return response

core/models.py
from datetime import timedelta

from django.conf import settings
from django.db import models
from django.db.models.signals import post_save
from django.shortcuts import reverse
from django.utils import timezone
from django_countries.fields import CountryField

CATEGORY_CHOICES = (
    ('GW', 'Giveaway'),
    ('PW', 'Pick Winner'),
    ('SB', 'Social Boost'),
    ('PE', 'Profile Examine')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('I', 'info'),
    ('W', 'success'),
    ('D', 'danger')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)

GIVEAWAY_STATUS_CHOICES = (
    ('I', 'In Cart'),
    ('P', 'Purchased'),
    ('S', 'Scheduled'),
    ('L', 'Live'),
    ('T', 'Winner Selected'),
    ('C', 'Winner Contacted'),
    ('D', 'Winner Paid')
)

SCHEDULER_QUEUE = (
    ('D', 'default'),
    ('L', 'low'),
    ('H', 'high')
)

PAYMENT_METHOD = (
    ('S', 'Stripe'),
    ('B', 'Braintree'),
    ('P', 'Paypal'),
    ('C', 'Bitcoin'),
    ('T', 'Credit'),
)


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user_profile')
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    braintree_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)
    twitch_account = models.CharField(max_length=250, null=True, blank=True)
    credit_display = models.BooleanField(default=True)
    
    def __str__(self):
        return str(self.user.username)


class Socials(models.Model):
    twitter = models.BooleanField(default=False)
    instagram = models.BooleanField(default=False)
    facebook = models.BooleanField(default=False)
    tiktok = models.BooleanField(default=False)
    # TODO ADD MORE SOCIALS
    # Could also integrate with socialauth so they have to have it confirmed before checkout


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    giveaway_value = models.FloatField(verbose_name="Amount to giveaway")  # Split value and fee to show amount given
    giveaway_fee = models.FloatField(verbose_name="Amount to charge buyer")
    duration_to_run = models.IntegerField(blank=True, null=True)
    # promote_socials = models.
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    available = models.BooleanField(default=True)
    priority = models.CharField(choices=SCHEDULER_QUEUE, max_length=1, default='D')
    description = models.TextField()
    image = models.ImageField()

    class Meta:
        default_related_name = 'items'
        ordering = ['-price']

    def __str__(self):
        return self.title

    def get_price(self):
        return self.giveaway_fee + self.giveaway_value

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey("Item", on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField(default=1)
    available_to_run = models.IntegerField(default=1)
    kind = models.IntegerField(default=0)
    slot = models.ForeignKey("Slotitem", on_delete=models.CASCADE, null=True)
    username = models.CharField(max_length=200, default='', blank=True, null=True)
    launch_code = models.CharField(max_length=200, blank=True, null=True)
    status = models.CharField(max_length=20, choices=GIVEAWAY_STATUS_CHOICES, default='I', blank=True, null=True)

    class Meta:
        ordering = ['-orders__id']

    def __str__(self):
        if self.kind == 0:
            return f"{self.quantity} of {self.item.title}"
        else:
            return f"{self.quantity} of {self.slot.title}"

    def get_title(self):
        if self.kind == 0:
            return self.item.title
        else:
            return self.slot.title

    def get_total_item_price(self):
        # self.user.related_field
        # self.user.account_type
        if self.kind == 0:
            price = (self.user.account_type.fee_quantifier * self.item.giveaway_fee) + self.item.giveaway_value
            # return self.quantity * self.item.get_price()
            return self.quantity * price
        else:
            return 0

    def get_total_discount_item_price(self):
        if self.kind == 0:
            return self.quantity * self.item.discount_price
        else:
            return 0

    def get_amount_saved(self):
        if self.kind == 0:
            return self.get_total_item_price() - self.get_total_discount_item_price()
        else:
            return 0

    def get_final_price(self):
        if self.kind == 0:
            if self.item.discount_price:
                return self.get_total_discount_item_price()
            return self.get_total_item_price()
        else:
            return self.quantity * self.slot.value

    def decrease_available(self):
        self.available_to_run -= 1

    def increase_available(self):
        self.available_to_run += 1


def get_deadline():
    return timezone.now() + timedelta(days=5)


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    expires_on = models.DateTimeField(default=get_deadline)
    desired_giveaway_date = models.DateTimeField(default=timezone.now, blank=True)
    ordered_date = models.DateTimeField(auto_now_add=True)
    ordered = models.BooleanField(default=False)
    kind = models.IntegerField(default=0)
    status = models.CharField(max_length=20, choices=GIVEAWAY_STATUS_CHOICES, default='I', blank=True, null=True)
    notes = models.TextField(blank=True, max_length=500)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    creditpayment = models.ForeignKey(
        'CreditPayment', related_name='paid_order', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    '''
    1. Item added to cart
    2. Adding a billing address
    (Failed checkout)
    3. Payment
    (Preprocessing, processing, packaging etc.)
    4. Being delivered
    5. Received
    6. Refunds
    '''

    class Meta:
        default_related_name = 'orders'
        ordering = ['-id']

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total

    def get_available_runs(self):
        # return ', '.join([x.item.title for x in self.items.all()])
        return ', '.join([x.item.title for x in self.items.filter(kind=0)])

    def get_purchased_items(self):
        # return ', '.join([x.item.title for x in self.items.all()])
        if self.kind == 0:
            return ', '.join([x.item.title for x in self.items.filter(kind=0).select_related('item')])
        else:
            return ', '.join([x.slot.title for x in self.items.filter(kind=1).select_related('item')])

    def get_items_sum(self):
        # return sum([y.quantity for y in self.items.all()])
        if self.kind == 0:
            return sum([y.quantity for y in self.items.filter(kind=0)])
        else:
            return sum([y.quantity for y in self.items.filter(kind=1)])


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'

class CreditPayment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    usd_amount = models.FloatField(default=0)
    credit_amount = models.FloatField(default=0)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        if self.user:
            return self.user.username + " : " + str(self.credit_amount)
        else:
            return '_' + " : " + str(self.credit_amount)
        

class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)

templates/shop/footer.html
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.twitter.com/gridgamingIO" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2020 Copyright:
      <a href="https://www.gridgaming.io" target="_blank"> gridgaming.io </a>
    </div>
    <!--/.Copyright-->

  </footer>

templates/shop/home.html
{% extends "shop/base.html" %}
<!-- old -->
{% block content %}
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Packages
                <span class="sr-only">(current)</span>
              </a>
            </li>
          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <div class="row wow fadeIn">

          {% for item in object_list %}
          <div class="col-lg-3 col-md-6 mb-4">

            <div class="card">

              <div class="view overlay">
                {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top" {% endcomment %}
                <img src="{{ item.image.url }}" class="card-img-top">
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

              <div class="card-body text-center">
                <a href="" class="grey-text">
                  <h5>{{ item.get_category_display }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>$
                  {% if item.discount_price %}
                  {{ item.discount_price }}
                  {% else %}
                  {{ item.price }}
                  {% endif %}
                  </strong>
                </h4>

              </div>

            </div>

          </div>
          {% endfor %}
        </div>

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->

      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-teal">

          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}

    </div>
  </main>

{% endblock content %}

templates/shop/navbar.html
{% load cart_template_tags %}



<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="/">
        <strong class="blue-text">Grid Gaming</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          {% comment %} <li class="nav-item active">
            <a class="nav-link waves-effect" href="/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="/checkout">
            Checkout</a>
          </li> {% endcomment %}
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
              <span class="clearfix d-none d-sm-inline-block"> Logout </span>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_login' %}">
              <span class="clearfix d-none d-sm-inline-block"> Login </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
              <span class="clearfix d-none d-sm-inline-block"> Signup </span>
            </a>
          </li>
          {% endif %}
        </ul>
      </div>

    </div>
  </nav>

templates/shop/order_snippet.html
{% load static %}
{% load mathfilters %}
{% load humanize %}
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Your cart</span>
    <span class="badge badge-megna badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
        {% if order_item.kind == 0 %}
        <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
            <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
            <small class="text-muted">{{ order_item.item.description}}</small>
            </div>
            <span class="text-muted">
                {% if user.user_profile.credit_display %}
                <img src="{% static 'assets/images/coin-xs.png' %}" style="padding-top:2px;width: 16px; vertical-align: text-top;">
                {{order_item.get_final_price|mul:cc_per_usd|intcomma}}
                {% else %}
                ${{ order_item.get_final_price }}
                {% endif %}
                
            </span>
        </li>
        {% else %}
        <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
            <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.slot.title}}</h6>
            <small class="text-muted">{{ order_item.slot.description}}</small>
            </div>
            <span class="text-muted">
                {% if user.user_profile.credit_display %}
                <img src="{% static 'assets/images/coin-xs.png' %}" style="padding-top:1px;width: 16px; vertical-align: text-top;">
                {{order_item.get_final_price|mul:cc_per_usd|intcomma}}
                {% else %}
                ${{ order_item.get_final_price }}
                {% endif %}
            </span>
        </li>
        {% endif %}
    {% endfor %}
    {% if order.coupon %}
    <li class="list-group-item d-flex justify-content-between bg-light">
        <div class="text-success">
        <h6 class="my-0">Promo code</h6>
        <small>{{ order.coupon.code }}</small>
        </div>
        <span class="text-success">-${{ order.coupon.amount }}</span>
    </li>
    {% endif %}
    <li class="list-group-item d-flex justify-content-between">
        <span>
            {% if user.user_profile.credit_display %}
            Total (Credit)
            {% else %}
            Total (USD)
            {% endif %}
        </span>
        <strong class="text-warning">
            {% if user.user_profile.credit_display %}
            <img src="{% static 'assets/images/coin-xs.png' %}" style="padding-top:1px;width: 16px; vertical-align: text-top;">
            {{order.get_total|mul:cc_per_usd|intcomma}}
            {% else %}
            ${{ order.get_total }}
            {% endif %}
        </strong>
    </li>
    </ul>

    {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
            <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
            </div>
        </div>
    </form>
    {% endif %}

</div>

templates/shop/order_summary.html
{% extends "shop/base.html" %}

{% block content %}
  <main>
    <div class="container">

    <div class="table-responsive text-nowrap">
    <h2>Order Summary</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Item title</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total Item Price</th>
        </tr>
        </thead>
        <tbody>
        {% for order_item in object.items.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order_item.item.title }}</td>
            <td>{{ order_item.item.price }}</td>
            <td>
                <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                {{ order_item.quantity }}
                <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
            </td>
            <td>
            {% if order_item.item.discount_price %}
                ${{ order_item.get_total_discount_item_price }}
                <span class="badge badge-primary">Saving ${{ order_item.get_amount_saved }}</span>
            {% else %}
                ${{ order_item.get_total_item_price }}
            {% endif %}
            <a style='color: red;' href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                <i class="fas fa-trash float-right"></i>
            </a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan='5'>Your cart is empty</td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-primary float-right' href='{%  url 'core:home' %}'>Continue shopping</a>
            </td>
        </tr>
        {% endfor %}
        {% if object.coupon %}
        <tr>
            <td colspan="4"><b>Coupon</b></td>
            <td><b>-${{ object.coupon.amount }}</b></td>
        </tr>
        {% endif %}
        {% if object.get_total %}
        <tr>
            <td colspan="4"><b>Order Total</b></td>
            <td><b>${{ object.get_total }}</b></td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-warning float-right ml-2' href='{% url 'core:checkout' %}'>Proceed to checkout</a>
            <a class='btn btn-primary float-right' href='{%  url 'core:home' %}'>Continue shopping</a>
            </td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    </div>

    </div>
  </main>

{% endblock content %}

templates/shop/product.html
{% extends "shop/base.html" %}

{% block content %}

  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="{{ object.image.url }}" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
              </a>
            </div>

            <p class="lead">
              {% if object.discount_price %}
              <span class="mr-1">
                <del>${{ object.price }}</del>
              </span>
              <span>${{ object.discount_price }}</span>
              {% else %}
              <span>${{ object.price }}</span>
              {% endif %}
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{ object.description }}</p>

            {% comment %} <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">
                Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> {% endcomment %}
            <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
              Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
              Remove from cart
            </a>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>You will be notified of scheduled date automatically. You can pay extra to "launch now" or go with the economy option. You will have the option to draw the winner and links to the giveaway will be automatic. GridGaming will take care of payment distribution to winners. </p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>

{% endblock content %}

templates/shop/request_refund.html
{% extends "shop/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <main>
    <div class="container">

    <h2>Request Refund</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-primary'>Submit</button>
    </form>

    </div>
  </main>

{% endblock content %}