core/urls.py
from django.shortcuts import render_to_response
from django.urls import path, re_path, include
from django.contrib.auth.decorators import login_required
from .views import (
    ItemDetailView,
    CheckoutViewV2,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    BitpayView,
    #PaymentStripeView,
    #PaymentMainView,
    AddCouponView,
    RequestRefundView,
    OrderView,
    AllOrderView,
    DisableView,
    AccountView,
    PaypalPaymentProcess,
    payment_done,
    payment_canceled,
    bitpay_notify,
    coinbase_notify,
    CoinbaseView
)

app_name = 'core'

urlpatterns = [
    path('', login_required(HomeView.as_view()), name='home'),
    path('checkout/', login_required(CheckoutViewV2.as_view()), name='checkout'),
    path('order-summary/', login_required(OrderSummaryView.as_view()), name='order-summary'),
    path('orders/', login_required(OrderView.as_view()), name='user-orders'),
    path('all-orders/', login_required(AllOrderView.as_view()), name='all-orders'),
    path('accounts/', login_required(AccountView.as_view()), name='accounts'),
    path('disable/', login_required(DisableView.as_view()), name='disable'),
    path('product/<slug>/', login_required(ItemDetailView.as_view()), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', login_required(AddCouponView.as_view()), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    #path('payment/', login_required(PaymentStripeView.as_view()), name='payment-stripe'),
    path('payment/', login_required(PaymentView.as_view()), name='payment'),
    path('bitpay/', login_required(BitpayView.as_view()), name='bitpay'),
    path('bitpay-notify/', bitpay_notify, name='bitpay-notify'),
    path('coinbase-notify', coinbase_notify, name='coinbase-notify'),
    path('coinbase/', login_required(CoinbaseView.as_view()), name='coinbase'),
    path('request-refund/', login_required(RequestRefundView.as_view()), name='request-refund'),
    re_path(r'^paypal/',include('paypal.standard.ipn.urls')),
    re_path(r'^process/$', login_required(PaypalPaymentProcess.as_view()), name='process'),
    re_path(r'^done/$', payment_done, name='done'),
    re_path(r'^canceled/$', payment_canceled, name='canceled')

]

def handler404(request, template_name="404.html"):
    response = render_to_response(template_name)
    response.status_code = 404
    return response

frontend/urls.py
from django.urls import path, include, re_path
from .views import index, home, profile, account_type, update_account_type, pre_checkout, CheckoutView, PaypalPaymentView, payment_canceled, payment_done, StripePaymentView, get_membership, CoinbasePaymentView, CreditView, set_membership_alert
from django.contrib.auth.decorators import login_required

app_name = 'frontend'

urlpatterns = [
    # path('', index, name='index'),
    path('', home, name='home'),
    path('profile', profile, name='profile'),
    path('profile/get_membership', get_membership, name='get_membership'),
    path('profile/set_membership_alert', set_membership_alert, name='set_membership_alert'),
    path('profile/account_type', account_type, name='account_type'),
    path('profile/update_account_type', update_account_type, name='update_account_type'),
    path('pre_checkout', pre_checkout, name='pre_checkout'),
    path('checkout', login_required(CheckoutView.as_view()), name='checkout'),
    path('wallet', login_required(CreditView.as_view()), name='credits'),
    path('wallet/paypalpayment', login_required(PaypalPaymentView.as_view()), name='paypalpayment'),
    path('wallet/stripepayment', login_required(StripePaymentView.as_view()), name='stripepayment'),
    path('wallet/coinbasepayment', login_required(CoinbasePaymentView.as_view()), name='coinbasepayment'),
    path('wallet/payment_done', payment_done, name='payment_done'),
    path('wallet/payment_canceled', payment_canceled, name='payment_canceled'),
    re_path(r'^paypal/',include('paypal.standard.ipn.urls')),
]

core/models.py
from datetime import timedelta

from django.conf import settings
from django.db import models
from django.db.models.signals import post_save
from django.shortcuts import reverse
from django.utils import timezone
from django_countries.fields import CountryField

CATEGORY_CHOICES = (
    ('GW', 'Giveaway'),
    ('PW', 'Pick Winner'),
    ('SB', 'Social Boost'),
    ('PE', 'Profile Examine')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('I', 'info'),
    ('W', 'success'),
    ('D', 'danger')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)

GIVEAWAY_STATUS_CHOICES = (
    ('I', 'In Cart'),
    ('P', 'Purchased'),
    ('S', 'Scheduled'),
    ('L', 'Live'),
    ('T', 'Winner Selected'),
    ('C', 'Winner Contacted'),
    ('D', 'Winner Paid')
)

SCHEDULER_QUEUE = (
    ('D', 'default'),
    ('L', 'low'),
    ('H', 'high')
)

PAYMENT_METHOD = (
    ('S', 'Stripe'),
    ('B', 'Braintree'),
    ('P', 'Paypal'),
    ('C', 'Bitcoin'),
    ('T', 'Credit'),
)


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user_profile')
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    braintree_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)
    twitch_account = models.CharField(max_length=250, null=True, blank=True)
    credit_display = models.BooleanField(default=True)
    
    def __str__(self):
        return str(self.user.username)


class Socials(models.Model):
    twitter = models.BooleanField(default=False)
    instagram = models.BooleanField(default=False)
    facebook = models.BooleanField(default=False)
    tiktok = models.BooleanField(default=False)
    # TODO ADD MORE SOCIALS
    # Could also integrate with socialauth so they have to have it confirmed before checkout


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    giveaway_value = models.FloatField(verbose_name="Amount to giveaway")  # Split value and fee to show amount given
    giveaway_fee = models.FloatField(verbose_name="Amount to charge buyer")
    duration_to_run = models.IntegerField(blank=True, null=True)
    # promote_socials = models.
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    available = models.BooleanField(default=True)
    priority = models.CharField(choices=SCHEDULER_QUEUE, max_length=1, default='D')
    description = models.TextField()
    image = models.ImageField()

    class Meta:
        default_related_name = 'items'
        ordering = ['-price']

    def __str__(self):
        return self.title

    def get_price(self):
        return self.giveaway_fee + self.giveaway_value

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey("Item", on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField(default=1)
    available_to_run = models.IntegerField(default=1)
    kind = models.IntegerField(default=0)
    slot = models.ForeignKey("Slotitem", on_delete=models.CASCADE, null=True)
    username = models.CharField(max_length=200, default='', blank=True, null=True)
    launch_code = models.CharField(max_length=200, blank=True, null=True)
    status = models.CharField(max_length=20, choices=GIVEAWAY_STATUS_CHOICES, default='I', blank=True, null=True)

    class Meta:
        ordering = ['-orders__id']

    def __str__(self):
        if self.kind == 0:
            return f"{self.quantity} of {self.item.title}"
        else:
            return f"{self.quantity} of {self.slot.title}"

    def get_title(self):
        if self.kind == 0:
            return self.item.title
        else:
            return self.slot.title

    def get_total_item_price(self):
        # self.user.related_field
        # self.user.account_type
        if self.kind == 0:
            price = (self.user.account_type.fee_quantifier * self.item.giveaway_fee) + self.item.giveaway_value
            # return self.quantity * self.item.get_price()
            return self.quantity * price
        else:
            return 0

    def get_total_discount_item_price(self):
        if self.kind == 0:
            return self.quantity * self.item.discount_price
        else:
            return 0

    def get_amount_saved(self):
        if self.kind == 0:
            return self.get_total_item_price() - self.get_total_discount_item_price()
        else:
            return 0

    def get_final_price(self):
        if self.kind == 0:
            if self.item.discount_price:
                return self.get_total_discount_item_price()
            return self.get_total_item_price()
        else:
            return self.quantity * self.slot.value

    def decrease_available(self):
        self.available_to_run -= 1

    def increase_available(self):
        self.available_to_run += 1


def get_deadline():
    return timezone.now() + timedelta(days=5)


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    expires_on = models.DateTimeField(default=get_deadline)
    desired_giveaway_date = models.DateTimeField(default=timezone.now, blank=True)
    ordered_date = models.DateTimeField(auto_now_add=True)
    ordered = models.BooleanField(default=False)
    kind = models.IntegerField(default=0)
    status = models.CharField(max_length=20, choices=GIVEAWAY_STATUS_CHOICES, default='I', blank=True, null=True)
    notes = models.TextField(blank=True, max_length=500)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    creditpayment = models.ForeignKey(
        'CreditPayment', related_name='paid_order', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    '''
    1. Item added to cart
    2. Adding a billing address
    (Failed checkout)
    3. Payment
    (Preprocessing, processing, packaging etc.)
    4. Being delivered
    5. Received
    6. Refunds
    '''

    class Meta:
        default_related_name = 'orders'
        ordering = ['-id']

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total

    def get_available_runs(self):
        # return ', '.join([x.item.title for x in self.items.all()])
        return ', '.join([x.item.title for x in self.items.filter(kind=0)])

    def get_purchased_items(self):
        # return ', '.join([x.item.title for x in self.items.all()])
        if self.kind == 0:
            return ', '.join([x.item.title for x in self.items.filter(kind=0).select_related('item')])
        else:
            return ', '.join([x.slot.title for x in self.items.filter(kind=1).select_related('item')])

    def get_items_sum(self):
        # return sum([y.quantity for y in self.items.all()])
        if self.kind == 0:
            return sum([y.quantity for y in self.items.filter(kind=0)])
        else:
            return sum([y.quantity for y in self.items.filter(kind=1)])


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'

class CreditPayment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    usd_amount = models.FloatField(default=0)
    credit_amount = models.FloatField(default=0)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        if self.user:
            return self.user.username + " : " + str(self.credit_amount)
        else:
            return '_' + " : " + str(self.credit_amount)
        

class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)

frontend/models.py
from core.models import Order, OrderItem, Payment               
from django.conf import settings
from django.db import models
import uuid

PAYMENT_CHOICES = (
    ('W', 'Waiting'),
    ('P', 'Pending'),
    ('C', 'Complete'),
)

class BuyCredit(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    credit_amount = models.IntegerField(default=0)
    usd_amount = models.FloatField(default=0)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    payment_status = models.CharField(choices=PAYMENT_CHOICES, max_length=1, default='W')
    added_credit = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['id']

class OneValue(models.Model):
    cc_per_usd = models.IntegerField(default=1)
    min_buy_credit = models.IntegerField(default=5)
    judge_credit_price = models.IntegerField(default=1)
    ads = models.TextField(default='', blank=True)
    class Meta:
        ordering = ['id']

frontend/forms.py
from django import forms
from users.models import UserRoles


# class UserAccountForm(forms.ModelForm):
#
#     account_type = forms.ChoiceField(choices=ROLE_CHOICES, widget=forms.RadioSelect())
#
#     class Meta:
#         model = UserRoles
#         fields = ('role_name', )
#
#
#     # def __init__(self, *args, **kwargs):
#     #     super(UserAccountForm, self).__init__(*args, **kwargs)
#     #     self.fields['role_name'].widget = forms.RadioSelect()
#

class UserAccountForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super(UserAccountForm, self).__init__(*args, **kwargs)

        choices = [(role, role.role_description)
                   for role in UserRoles.objects.all()]

        self.fields['user_roles'] = forms.ChoiceField(widget=forms.RadioSelect(),
                                                      choices=choices, label='')

templates/frontend/canceled.html
{% extends "core/base.html" %}
{% block content %}
 
    <p>Payment cancelled.</p>
 
{% endblock %}

templates/frontend/checkout.html
{% extends "core/base.html" %}
{% load static %}
{% load cart_template_tags %}
{% load crispy_forms_tags %}
{% block extra_css %}
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
{% endblock extra_css %}

{% block content %}

<div class="container-fluid">
    <h2 class="my-5 h2 text-center">Checkout form</h2>
    <div class="row">
        <div class="col-md-2 col-lg-3"></div>
        <div class="col-md-8 col-lg-6 mb-4">
            <div class="card">
                <div class="card-body">
                    <div class="mt-4">
                    {% if reason == 'membership' %}
                        <h4>You are going to pay ${{uo.amount}} to upgrade membership.</h4>
                    {% else %}
                        <h5>You are going to pay ${{uo.amount}} to load all entries.</h5>
                    {% endif %}
                    <h6 class="mt-3">Please select payment method and then continue to checkout.</h6>
                    </div>
                    <form action="{% url 'frontend:checkout' %}" method="POST" class="form-material mt-4">
                        {% csrf_token %}
                        <!-- <input type="hidden" name="reason" value="{{uo.reason}}">
                        <input type="hidden" name="uoid" value="{{uoid}}"> -->
                        <div class="mt-4">
                            <h2>Payment Option</h2>
                            <div>
                                <!-- <div class="custom-control custom-radio my-2">
                                    <input id="in_paypal" name="payment_option" value="paypal" type="radio" class="custom-control-input" checked required>
                                    <label class="custom-control-label" for="in_paypal">Paypal</label>
                                </div> -->
                                <div class="custom-control custom-radio my-2">
                                    <input id="in_stripe" name="payment_option" value="stripe" type="radio" class="custom-control-input" required>
                                    <label class="custom-control-label" for="in_stripe">Stripe</label>
                                </div>
                                <div class="custom-control custom-radio my-2">
                                    <input id="in_coinbase" name="payment_option" value="coinbase" type="radio" class="custom-control-input" required>
                                    <label class="custom-control-label" for="in_coinbase">Crypto</label>
                                </div>
                            </div>
                        </div>
                        <button class="btn btn-megna btn-lg btn-block mt-4" type="submit">Continue to checkout</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock content %}

{% block extra_scripts %}

{% endblock extra_scripts %}

templates/frontend/credits_backup.html
{% extends "core/base.html" %}
{% load static %}

{% block extra_head_tags %}
<link href="{% static 'assets/libs/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.css' %}" rel="stylesheet" />
<!-- <link href="{% static 'css/style.min.css' %}" rel="stylesheet" /> -->


{% endblock %} 

{% block extra_css %}
<style>
    #div_credits h2, #div_credits span{
        transition-property: all;
        transition-duration: 0.5s;
    }
    #current_credits{
        font-size: 72px;
    }
    .credits-flex #div_credits{
        display: flex;
        justify-content: center;
    }
    .credits-flex #current_credits{
        font-size: 30px;
    }
    #div_container.credits-flex hr{
        display: block;
    }
    #div_container hr{
        display: none;
    }
    #div_checkout{
        display: none;
    }
    #div_container.credits-flex #btn_buy{
        display: none;
    }
    #div_container.credits-flex #div_checkout{
        display: block;
    }
    #div_checkout .bootstrap-touchspin-injected{
        min-width: 200px;
        width: 50%;
        margin: auto;
    }
</style>
{% endblock extra_css %}

{% block content %}

<div class="container  text-center">
    <div class="jumbotron card card-image">
        <div id="div_container" class="text-white text-center py-5 px-4">
            <div id="div_credits" class="text-center">
                <h2 class="card-title h1-responsive pt-2 font-bold text-uppercase"><strong>You have</strong></h2>
                <span id="current_credits" class="text-primary mx-2">{{credit_amount}}</span>
                <h2 class="card-title h1-responsive pt-2 font-bold text-uppercase"><strong>Credits Now</strong></h2>
            </div>
            <h6 class="mb-5" id="credits_usd"><span>1</span> credit (c) = <span>{{credit_price}}</span> usd ($)</h6>
            <hr style="border-color: #21c1d6;">
            <button id="btn_buy" type="button"
                class="btn btn-lg btn-block font-medium btn-outline-success block-card"><i
                    class="fas fa-coins mx-2"></i>Buy Credits</button>
                   
            <div id="div_checkout" class="mt-5">
                <form action="{% url 'frontend:credits' %}" method="POST" class="form-material mt-4">
                    {% csrf_token %}
                    
                    <h4 class="mb-4 text-warning" id="sent_msg"> You need at least <span id="need_credit" class="text-danger">200</span> credits to checkout</h4>
                    <div class="form-group text-center mb-2">
                        <input id="in_credit" type="text" value="1" name="in_credit" class="col-md-8 form-control" style="width: 200px;">
                    </div>
                    <h4 class="mb-5" id="pay_usd"> = <span>{{credit_price}}</span> $</h4>
                    <div>
                        <h4>Pay with</h4>
                        <div class="mb-5" style="display: flex; justify-content: center;">
                            <div class="custom-control custom-radio my-2 mx-2">
                                <input id="in_stripe" name="payment_option" value="stripe" type="radio" class="custom-control-input" required>
                                <label class="custom-control-label" for="in_stripe">Stripe</label>
                            </div>
                            <div class="custom-control custom-radio my-2 mx-2">
                                <input id="in_coinbase" name="payment_option" value="coinbase" type="radio" class="custom-control-input" required>
                                <label class="custom-control-label" for="in_coinbase">Crypto</label>
                            </div>
                        </div>
                    </div>
                    <input id="cart_param" type="text" value="{{cart_param}}" name="cart_param" hidden>
                    <button id="btn_checkout" type="submit"
                    class="btn btn-lg btn-block font-medium btn-outline-success block-card"><i
                        class="fas fa-money-check-alt mx-2"></i> Checkout</button>
                </form>
            </div>
        </div>
    </div>
</div>
</div>


{% endblock content %}

{% block extra_scripts %}
<script src="{% static 'assets/libs/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.js' %}"></script>

<script>
    var credit_price = {{credit_price}}
    var credit_amount = {{credit_amount}}
    var need_param = '{{need_param}}'
    var cart_param = '{{cart_param}}'
    $(function(){
        if(need_param != ''){
            $("#need_credit").html(need_param)
            $("#in_credit").val(parseInt(need_param))
            $("#sent_msg").show()
            $("#div_container").addClass('credits-flex')
            show_usd();
        }else{
            $("#sent_msg").hide()
        }
        $("#btn_buy").click(function(){
            $("#div_container").addClass('credits-flex')
        })
        $("input[name='in_credit']").TouchSpin({
            min: 1,
            max: 10000,
            stepinterval: 5,
            maxboostedstep: 100,
            prefix: 'credits'
        });
        $("#in_credit").change(function(){
            show_usd()
        })
        function show_usd(){
            in_credit = parseInt($("#in_credit").val());
            pay_usd = parseFloat(in_credit * credit_price).toFixed(1)
            $("#pay_usd span").html(pay_usd);
        }
    })
</script>
{% endblock extra_scripts %}

templates/frontend/home.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
<!-- ============================================================== -->
<!-- Start Page Content -->
<!-- ============================================================== -->
<div class="row el-element-overlay">
    {% for item in object_list %}
    <div class="col-lg-3 col-md-6">
        <div class="card">
            <div class="el-card-item pb-3">
                <div class="el-card-avatar mb-3 el-overlay-1 w-100 overflow-hidden position-relative text-center"> <img src="{{ item.image.url }}" class="d-block position-relative w-100" alt="user" />
                    <div class="el-overlay w-100 overflow-hidden">
                        <ul class="list-style-none el-info text-white text-uppercase d-inline-block p-0">
                            <li class="el-item d-inline-block my-0  mx-1"><a class="btn default btn-outline image-popup-vertical-fit el-link text-white border-white" href="{{ item.image.url }}"><i class="icon-magnifier"></i></a></li>
                            <li class="el-item d-inline-block my-0  mx-1"><a class="btn default btn-outline el-link text-white border-white" href="{{ item.get_absolute_url }}"><i class="icon-link"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="d-flex no-block align-items-center">
                    <div class="ml-3">
                        <h4 class="mb-0">{{ item.get_category_display }}</h4>
                        <span class="text-muted">{{ item.title }}</span>
                    </div>
                    <div class="ml-auto mr-3">
                        <button type="button" class="btn {{ item.get_label_display }} btn-circle">
                      {% if item.discount_price %}
                      {{ item.discount_price }}
                      {% else %}
                      {{ item.price }}
                      {% endif %}
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endfor %}
    <div class="col-lg-3 col-md-6">
        <div class="card">
            <div class="el-card-item pb-3">
                <div class="el-card-avatar mb-3 el-overlay-1 w-100 overflow-hidden position-relative text-center"> <img src="{% static 'assets/images/gallery/chair2.jpg' %}" class="d-block position-relative w-100" alt="user" />
                    <div class="el-overlay w-100 overflow-hidden">
                        <ul class="list-style-none el-info text-white text-uppercase d-inline-block p-0">
                            <li class="el-item d-inline-block my-0  mx-1"><a class="btn default btn-outline image-popup-vertical-fit el-link text-white border-white" href="{% static 'assets/images/gallery/chair2.jpg' %}"><i class="icon-magnifier"></i></a></li>
                            <li class="el-item d-inline-block my-0  mx-1"><a class="btn default btn-outline el-link text-white border-white" href="javascript:void(0);"><i class="icon-link"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="d-flex no-block align-items-center">
                    <div class="ml-3">
                        <h4 class="mb-0">Rounded Chair</h4>
                        <span class="text-muted">globe type chair for rest</span>
                    </div>
                    <div class="ml-auto mr-3">
                        <button type="button" class="btn btn-success btn-circle">$15</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="card">
            <div class="el-card-item pb-3">
                <div class="el-card-avatar mb-3 el-overlay-1 w-100 overflow-hidden position-relative text-center"> <img src="{% static 'assets/images/gallery/chair3.jpg' %}" class="d-block position-relative w-100" alt="user" />
                    <div class="el-overlay w-100 overflow-hidden">
                        <ul class="list-style-none el-info text-white text-uppercase d-inline-block p-0">
                            <li class="el-item d-inline-block my-0  mx-1"><a class="btn default btn-outline image-popup-vertical-fit el-link text-white border-white" href="{% static 'assets/images/gallery/chair3.jpg' %}"><i class="icon-magnifier"></i></a></li>
                            <li class="el-item d-inline-block my-0  mx-1"><a class="btn default btn-outline el-link text-white border-white" href="javascript:void(0);"><i class="icon-link"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="d-flex no-block align-items-center">
                    <div class="ml-3">
                        <h4 class="mb-0">Rounded Chair</h4>
                        <span class="text-muted">globe type chair for rest</span>
                    </div>
                    <div class="ml-auto mr-3">
                        <button type="button" class="btn btn-dark btn-circle">$15</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

      <!--Pagination-->

      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-teal">

          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}
</div>
<!-- ============================================================== -->
<!-- End Page Content -->
<!-- ============================================================== -->
{% endblock %}

templates/frontend/paypalprocess.html
{% extends "core/base.html" %}
{% block content %}
    <h4>Pay with PayPal</h4>
    {{ form.render }}
{% endblock %}