core/urls.py
from django.shortcuts import render_to_response
from django.urls import path, re_path, include
from django.contrib.auth.decorators import login_required
from .views import (
    ItemDetailView,
    CheckoutViewV2,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    BitpayView,
    #PaymentStripeView,
    #PaymentMainView,
    AddCouponView,
    RequestRefundView,
    OrderView,
    AllOrderView,
    DisableView,
    AccountView,
    PaypalPaymentProcess,
    payment_done,
    payment_canceled,
    bitpay_notify,
    coinbase_notify,
    CoinbaseView
)

app_name = 'core'

urlpatterns = [
    path('', login_required(HomeView.as_view()), name='home'),
    path('checkout/', login_required(CheckoutViewV2.as_view()), name='checkout'),
    path('order-summary/', login_required(OrderSummaryView.as_view()), name='order-summary'),
    path('orders/', login_required(OrderView.as_view()), name='user-orders'),
    path('all-orders/', login_required(AllOrderView.as_view()), name='all-orders'),
    path('accounts/', login_required(AccountView.as_view()), name='accounts'),
    path('disable/', login_required(DisableView.as_view()), name='disable'),
    path('product/<slug>/', login_required(ItemDetailView.as_view()), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', login_required(AddCouponView.as_view()), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    #path('payment/', login_required(PaymentStripeView.as_view()), name='payment-stripe'),
    path('payment/', login_required(PaymentView.as_view()), name='payment'),
    path('bitpay/', login_required(BitpayView.as_view()), name='bitpay'),
    path('bitpay-notify/', bitpay_notify, name='bitpay-notify'),
    path('coinbase-notify', coinbase_notify, name='coinbase-notify'),
    path('coinbase/', login_required(CoinbaseView.as_view()), name='coinbase'),
    path('request-refund/', login_required(RequestRefundView.as_view()), name='request-refund'),
    re_path(r'^paypal/',include('paypal.standard.ipn.urls')),
    re_path(r'^process/$', login_required(PaypalPaymentProcess.as_view()), name='process'),
    re_path(r'^done/$', payment_done, name='done'),
    re_path(r'^canceled/$', payment_canceled, name='canceled')

]

def handler404(request, template_name="404.html"):
    response = render_to_response(template_name)
    response.status_code = 404
    return response

retweet_picker/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views
from .views import (
    OrdersListView,
    launch_giveaway,
    #prelaunch_validator,
    order_details,
    QueueListView,
    delete_queue,
    clear_queue,
    pick, draw, drawstop, fetch_data, import_contest, pick_entries, load_entries, load_entry_progress,
    load_all_entries, drawing_progress, draw_result
)

app_name = 'retweet_picker'

urlpatterns = [
    path('', OrdersListView.as_view(), name='giveaway-list'),
    path('new_contest/', views.new_retweet_contest, name='retweet_picker'),
    path('launch/<int:order_id>/<int:item_id>', launch_giveaway, name='launch_giveaway'),
    path('queue/', login_required(QueueListView.as_view()) , name='queue_view'),
    # path('queue/<str:queue_type>/', QueueListView.as_view() , name='queue_view'),
    path('delqueue', delete_queue , name='del_queue'),
    path('draw', draw , name='draw'),
    path('draw-result/<draw_id>', draw_result , name='draw_result'),
    path('drawstop', drawstop , name='drawstop'),
    path('drawing_progress', drawing_progress , name='drawing_progress'),
    path('fetch_data', fetch_data , name='fetch_data'),
    path('import_contest', import_contest , name='import_contest'),
    path('load_entries', load_entries , name='load_entries'),
    path('load_entry_progress', load_entry_progress , name='load_entry_progress'),
    path('load_all_entries', load_all_entries , name='load_all_entries'),
    path('draw/<int:gwid>', login_required(pick_entries) , name='pick_entries'),
    path('clearqueue', clear_queue , name='clear_queue'),
    path('order/<int:order_id>', order_details, name="order_details"),
    path('results/<int:order_id>', views.contest_results, name='contest_results'),
    #path('results/<uuid:giveaway_id>', views.contest_results, name='contest_results'),
    path('results/', views.contest_results, name='all_contest_results'),
    path('bubble_rescue/decoder_ring/<slug:secret_code>/', views.decoder_ring, name='decoder'),
    path('bubble_rescue/', views.bubble_rescue, name='bubble-rescue-5000'),
    path('import/', login_required(views.pick), name='pick'),
    path('user_settings/', login_required(views.user_settings), name='user_settings'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
]

templates/shop_v2/accounts.html
{% extends "core/base.html" %}
{% load static %}
{% load cart_template_tags %}
{% load crispy_forms_tags %}

{% block extra_css %}
<link href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="https://cdn.datatables.net/buttons/1.6.2/css/buttons.dataTables.min.css" rel="stylesheet">
<style>
    table.dataTable tbody tr{
        background: none!important;
    }
    #zero_config_filter label, .paginate_button, .dataTables_info{
        color: #b2b9bf!important;
    }
    #zero_config_filter label input{
        border-style: none!important;
        background-color: #a2a6ae!important;
    }
    .dt-button{
        background: none!important;
        background-color: #323743!important;
        color:  #b2b9bf!important;
    }
    
</style>
{% endblock extra_css %}




{% block content %}

    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <!-- Column -->
            <!-- TODO replace with datatables eventually -->
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <div>
                            {% if accounts %}
                        
                            <h3 class="mb-4">All Accounts who signed to Community Giveaway</h3>
                            <div class="table-responsive">
                                <div id="zero_config_wrapper"
                                    class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
                                    
                                    <div class="row" style="margin-left: 0; margin-right: 0;">
                                        <div class="col-sm-12">
                                            <table class="table product-overview dataTable no-footer" id="zero_config"
                                                role="grid" aria-describedby="zero_config_info">
                                                <thead>
                                                <tr role="row">
                                                    <th class="sorting" tabindex="0" aria-controls="zero_config" rowspan="1"
                                                        colspan="1" aria-label="Order ID: activate to sort column ascending"
                                                        style="width: 0px;">Account Name
                                                    </th>
                                                    <th class="sorting" tabindex="0" aria-controls="zero_config" rowspan="1"
                                                        colspan="1" aria-label="Product: activate to sort column ascending"
                                                        style="width: 0px;">User Email
                                                    </th>
                                                    <th class="sorting" tabindex="0" aria-controls="zero_config" rowspan="1"
                                                        colspan="1" aria-label="Quantity: activate to sort column ascending"
                                                        style="width: 0px;">User Name
                                                    </th>
                                                    <th class="sorting" tabindex="0" aria-controls="zero_config" rowspan="1"
                                                        colspan="1" aria-label="Date: activate to sort column ascending"
                                                        style="width: 0px;">Joined Date
                                                    </th>
                                                </tr>
                                                </thead>
                                                <tbody>

                                                {% for value in accounts %}
                                                <tr role="row">
                                                    <td>{{ value.username }}</td>
                                                    <td>{{ value.email}}</td>
                                                    <td>{{ value.name }}</td>
                                                    <td>{{ value.date}}</td>
                                                </tr>
                                                {% endfor %}
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% else %}
                            <h4> No signed up accounts yet!</h4>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            <!-- Column -->
        </div>
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right sidebar -->
        <!-- ============================================================== -->
        <!-- .right-sidebar -->
        <!-- ============================================================== -->
        <!-- End Right sidebar -->
        <!-- ============================================================== -->
    </div>
{% endblock content %}

{% block extra_scripts %}
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.print.min.js"></script>

    <script src="{% static 'assets/libs/moment/moment.js' %}"></script>
    <script src="{% static 'assets/libs/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js' %}"></script>
    <script>
        $('#zero_config').DataTable( {
                dom: 'Bfrtip',
                lengthMenu: [
                    [ 10, 25, 50, -1 ],
                    [ '10 rows', '25 rows', '50 rows', 'Show all' ]
                ],
                buttons: [
                'pageLength','csv', 'excel', 'pdf'
                ]
            } );
            
        // MAterial Date picker
        $('#mdate').bootstrapMaterialDatePicker({weekStart: 0, time: false});
        $('#timepicker').bootstrapMaterialDatePicker({format: 'HH:mm', time: true, date: false});
        $('#date-format').bootstrapMaterialDatePicker({format: 'dddd DD MMMM YYYY - HH:mm'});

        $('#min-date').bootstrapMaterialDatePicker({format: 'DD/MM/YYYY HH:mm', minDate: new Date()});
        $('#date-fr').bootstrapMaterialDatePicker({
            format: 'DD/MM/YYYY HH:mm',
            lang: 'fr',
            weekStart: 1,
            cancelText: 'ANNULER'
        });
        $('#date-end').bootstrapMaterialDatePicker({weekStart: 0});
        $('#date-start').bootstrapMaterialDatePicker({weekStart: 0}).on('change', function (e, date) {
            $('#date-end').bootstrapMaterialDatePicker('setMinDate', date);
        });
    </script>

    {#    <script>#}
    {#    $(document).ready(function(){#}
    {#        $('input[name=use_default_shipping]').click(function(){#}
    {#            if($(this).prop("checked") == true){#}
    {#                console.log("Checkbox is checked.");#}
    {#            }#}
    {#            else if($(this).prop("checked") == false){#}
    {#                console.log("Checkbox is unchecked.");#}
    {#            }#}
    {#        });#}
    {#    });#}
    {##}
    {#</script>#}
    <script>
        var hideable_billing_form = $('.hideable_billing_form');

        var use_default_billing = document.querySelector("input[name=use_default_billing]");


        use_default_billing.addEventListener('change', function () {
            if (this.checked) {
                hideable_billing_form.hide();
            } else {
                hideable_billing_form.show();
            }
        })

    </script>

{% endblock extra_scripts %}

templates/shop_v2/bitpay.html
{% extends "core/base.html" %}
{% block extra_head %}
    <style>
    </style>
{% endblock extra_head %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title text-cyan">Pay with Bitpay</h5>
                    <div class="row">
                        <div class="col-md-7">
                            <a id="btn_bitpay">
                                <img style="cursor: pointer;" src="https://test.bitpay.com/cdn/en_US/bp-btn-pay-currencies.svg">
                            </a>
                            <form action="." method="post" id="complete_form">
                                {% csrf_token %}
                                <input type="hidden" name="order_id" value="{{order_id}}">
                                <input type="hidden" name="invoice_id" value="{{invoice_id}}">
                                <div style="display: none;">
                                    <button>Submit Payment</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

{% block extra_scripts %}
    <script src="https://bitpay.com/bitpay.min.js"></script>
    <script language="javascript">
        var is_paid = false
        var invoice_id = '{{invoice_id}}'
        var order_id = '{{order_id}}'
        var env = '{{bitpay_env}}'
        function pay_complete(){
            $("#complete_form").submit()
        }
        bitpay.onModalWillEnter(function() {
            console.log('modal is opening');
        });

        bitpay.onModalWillLeave(function() {
            console.log('modal is closing');
        });

        window.addEventListener("message", function (event) {
          payment_status = event.data.status;
          if (payment_status == "paid") {
            is_paid = true
            pay_complete()
            return;
          } 
        }, false);
        //show the order info
        bitpay.onModalWillLeave(function () {
            if (is_paid == false) {
                console.log("bitpay paid false")
            } 
        });
        //show the modal
        if(env == 'test'){
          bitpay.enableTestMode()
        }
        $(function(){
            $("#btn_bitpay").click(function(){
                bitpay.showInvoice(invoice_id)
            })
        })
        
      </script>
{% endblock extra_scripts %}

templates/shop_v2/cart.html
{% extends "core/base.html" %}
{% load cart_template_tags %}
{% load mathfilters %}
{% load humanize %}
{% load static %}

{% block content %}
    <div class="row">
        <!-- Column -->
        <div class="col-md-9 col-lg-9">
            <h3> Order Summary</h3>
        {% for social in social_boost %}
        {{ social.title }}
        {% endfor %}
            <div class="card">
                <div class="card-header bg-primary">
                    <h5 class="mb-0 text-white float-md-left">Your Cart</h5>
                    <h5 class="mb-0 text-white float-md-right">Item Count: <strong>{{ request.user|cart_item_count }}</strong></h5>
                </div>
                <div class="card-body">
                    <div class="progress mb-2 progress-xl" style="border-radius: 0;">
                        <div class="progress-bar progress-bar-striped progress-bar-animated bg-{{progress_class}}" role="progressbar" aria-valuenow="{{credit_percent}}" aria-valuemin="0" aria-valuemax="100" style="width: {{credit_percent}}%">
                            Your Wallet
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table class="table product-overview">
                            <thead>
                            <tr>
                                <th>Image</th>
                                <th>Product info</th>
                                <th>Price</th>
                                <th>Quantity</th>
                                <th style="text-align:center">Total</th>
                                <th style="text-align:center">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for order_item in object.items.all %}
                            {% if order_item.kind == 0 %}
                                <tr>
                                    <td width="150"><img src="{{ order_item.item.image.url }}" alt="" width="80">
                                    </td>
                                    <td width="550">
                                        <h5 class="font-500">{{ order_item.item.title }}</h5>
                                        <p>{{ order_item.item.description }}</p>

                                    </td>

                                    <td class="font-500" width="150">
                                        {% if user.user_profile.credit_display %}
                                        <img src="{% static 'assets/images/coin-xs.png' %}" style="padding-top:2px;width: 16px; vertical-align: text-top;">
                                        {{ order_item.item.giveaway_fee|mul:user.account_type.fee_quantifier|add:order_item.item.giveaway_value|mul:cc_per_usd|floatformat:0|intcomma}}
                                        {% else %}
                                        ${{ order_item.item.giveaway_fee|mul:user.account_type.fee_quantifier|add:order_item.item.giveaway_value|floatformat:0 }}
                                        {% endif %}
                                    </td>
                                        <td width="70" align="center" class="font-500">
                                        <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i
                                                class="fas fa-minus mr-2"></i></a>
                                        {{ order_item.quantity }}
                                        <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i
                                                class="fas fa-plus ml-2"></i></a>
                                    </td>
                                    <td width="150" align="center">
                                        {% if order_item.item.discount_price %}
                                            {% if user.user_profile.credit_display %}
                                            <img src="{% static 'assets/images/coin-xs.png' %}" style="padding-top:2px;width: 16px; vertical-align: text-top;">
                                            {{ order_item.get_total_discount_item_price|mul:cc_per_usd|intcomma }}
                                            {% else %}
                                            ${{ order_item.get_total_discount_item_price }}
                                            {% endif %}
                                            <span class="badge badge-primary">Saving ${{ order_item.get_amount_saved }}</span>
                                        {% else %}
                                            {% if user.user_profile.credit_display %}
                                            <img src="{% static 'assets/images/coin-xs.png' %}" style="padding-top:2px;width: 16px; vertical-align: text-top;">
                                            {{ order_item.get_total_item_price|mul:cc_per_usd|intcomma}}
                                            {% else %}
                                            ${{ order_item.get_total_item_price }}
                                            {% endif %}
                                        {% endif %}
                                    </td>


                                    <td align="center"><a href="{% url 'core:remove-from-cart' order_item.item.slug %}"
                                                          class="text-inverse" title=""
                                                          data-toggle="tooltip" data-original-title="Delete"><i
                                            class="ti-trash text-dark"></i></a></td>
                                </tr>
                            {% endif %}
                            {% endfor %}
                            </tbody>
                        </table>
                        <hr>
                        <div class="d-flex no-block align-items-center">
                            <a href="{% url 'core:home' %}">
                                <button class="btn btn-dark btn-outline"><i class="fas fa-arrow-left"></i> Continue
                                    shopping
                            </a>
                            </button>
                            <div class="ml-auto">
                                <a href="{% url 'core:checkout' %}">
                                    <button class="btn btn-danger"><i class="fa fa fa-shopping-cart"></i> Checkout
                                    </button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Column -->
        <div class="col-md-3 col-lg-3">

            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">CART SUMMARY</h5>
                    {% if object.get_total %}
                        <hr>
                        <small>Total Price</small>
                        <h2>
                            {% if user.user_profile.credit_display %}
                            <img src="{% static 'assets/images/coin-xs.png' %}" style="padding-top:3px;width: 25px; vertical-align: text-top;">
                            {{ object.get_total|mul:cc_per_usd|intcomma}}
                            {% else %}
                            ${{ object.get_total }}
                            {% endif %}
                            
                        </h2>
                        <hr>
                        <a href="{% url 'core:checkout' %}">
                            <button class="btn btn-success">Checkout</button>
                        </a>
                        <!--<button class="btn btn-secondary btn-outline">Cancel</button>-->
                    {% endif %}
                </div>
            </div>
        {% if DISPLAY_COUPON_FORM %}
        <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
            {% csrf_token %}
            <div class="input-group">
                {{ couponform.code }}
                <div class="input-group-append">
                <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
                </div>
            </div>
        </form>
        {% endif %}
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Need Assistance?</h5>
                    <hr>
                    <h6><a href="mailto:business@gridgaming.io?subject=testtest"><i class="ti-email"></i> business@gridgaming.io</a></h6> <small>Please contact with us if you have
                    any questions. Please allow 24-48 hours for a response.</small>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/shop_v2/coinbase.html
{% extends "core/base.html" %}
{% block extra_head %}
    <style>
    </style>
{% endblock extra_head %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title text-cyan">Pay with Coinbase</h5>
                    <div class="row">
                        <div class="col-md-7">
                            <div>
                                <a class="donate-with-crypto"
                                   href="https://commerce.coinbase.com/checkout/{{checkout_id}}">
                                  <span>Pay with Crypto</span>
                                </a>
                                <script src="https://commerce.coinbase.com/v1/checkout.js?version=201807">
                                </script>
                            </div>
                            <form action="." method="post" id="complete_form">
                                {% csrf_token %}
                                <input type="hidden" name="order_id" value="{{order_id}}">
                                <input type="hidden" name="checkout_id" value="{{checkout_id}}">
                                <div style="display: none;">
                                    <button>Submit Payment</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

{% block extra_scripts %}
    <script language="javascript">
        var is_paid = false
        var invoice_id = '{{checkout_id}}'
        var order_id = '{{order_id}}'
        
        BuyWithCrypto.registerCallback('onSuccess', function(e){
            // Charge was successfully completed
            pay_complete()
        });

        BuyWithCrypto.registerCallback('onFailure', function(e){
            // Charge failed
        });

        BuyWithCrypto.registerCallback('onPaymentDetected', function(e){
            // Payment has been detected but not yet confirmed
        });

        function pay_complete(){
            $("#complete_form").submit()
        }
        
        $(function(){
        })
        
      </script>
{% endblock extra_scripts %}

templates/shop_v2/done.html
{% extends "core/base.html" %}
{% load static %}
{% block content %}
 
<div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <img class="card-img-top" src="{% static 'img/order_complete.png' %}" alt="Card image cap" style="max-height: 450px">
                            <div class="card-img-overlay">
                                <div class="text-success">
                                    <span class="text-center font-14 mb-0"><i class="fas fa-check-circle font-18"> </i> <span class="font-18 mb-0"> Payment Processed</span></span>
                                    <p>
                                    <span class="text-white"> Order Item(s): {{ purchased_items}}<br>
                                        Total Charged: {{ total_charged }}<br>
                                        Order Reference: {{ ref_code }}<br>
                                            <span class="font-20"></span>
                                    </span>
                                    </p>
{#                                    #}
                                </div>
                            </div>
                            <div class="card-footer bg-white">
                                <div class="row">
                                    <div class="col-12">
                                        <div class="row text-center">
                                            <div class="col-12 col-md-4 border-right">
                                                <div class="mb-2">Start Giveaway</div>
                                                <div>
                                                    <a href="{% url 'retweet_picker:giveaway-list' %}"><button type="button" class="btn btn-outline-primary btn-rounded"><i class="mdi mdi-rocket mb-2"></i>Visit Launchpad</button></a>
                                                </div>
                                            </div>
                                            <div class="col-12 col-md-4 border-right">
                                                <div class="mb-2">See All Transactions</div>
                                                <div>
                                                    <a href="{% url 'core:user-orders' %}"><button type="button" class="btn btn-outline-success btn-rounded"><i class="mdi mdi-reorder-horizontal mb-2"></i>Review Orders</button></a>
                                                </div>
                                            </div>
                                            <div class="col-12 col-md-4">
                                                <div class="mb-2">Sponsor Another</div>
                                                <div>
                                                    <a href="{% url 'core:home' %}"><button type="button" class="btn btn-outline-info btn-rounded"><i class="mdi mdi-twitter mb-2"></i> Visit Shop</button></a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
{% endblock %}

templates/shop_v2/process.html
{% extends "core/base.html" %}
{% block content %}
    <h4>Pay with PayPal</h4>
    {{ form.render }}


{% endblock %}